
CREATE TABLE STUDENT_22_BLESSON( ROLL_NO INT PRIMARY KEY,
S_NAME VARCHAR(20),
PHYSICS INT,
CHEMISTRY INT, MATHEMATICS INT )
INSERT INTO STUDENT_22_BLESSON VALUES(1, ‘Adam’,20,20,33); 
INSERT INTO STUDENT_22_BLESSON VALUES(2, ‘Bob’,18,9,41); 
INSERT INTO STUDENT_22_BLESSON VALUES(3, ‘Bright’,22,7,31); 
INSERT INTO STUDENT_22_BLESSON VALUES(4, ‘Duke’,13,21,20); 
INSERT INTO STUDENT_22_BLESSON VALUES(5, ‘Elvin’,22,7,31); 
INSERT INTO STUDENT_22_BLESSON VALUES(6, ‘Fletcher’,2,10,48); 
INSERT INTO STUDENT_22_BLESSON VALUES(7, ‘Georgina’,22,12,22); 
INSERT INTO STUDENT_22_BLESSON VALUES(8, ‘Mary’,24,14,31); 
INSERT INTO STUDENT_22_BLESSON VALUES(9, ‘Tom’,19,15,24); 
INSERT INTO STUDENT_22_BLESSON VALUES(10, ‘Zack’,8,20,36);
SELECT * FROM STUDENT_22_BLESSON;

1) SELECT AVG(PHYSICS) FROM STUDENT_22_BLESSON;
2) SELECT MAX(MATHEMATICS) AS HIGHEST_MATHS_MARKS FROM STUDENT_22_BLESSON;
3) SELECT MIN(CHEMISTRY) AS LOWEST_MARK_CHEMISTRY FROM STUDENT_22_BLESSON;
4) SELECT COUNT(PHYSICS) FROM STUDENT_22_BLESSON WHERE PHYSICS>11;
5) SELECT S_NAME AS ALL_PASS FROM STUDENT_22_BLESSON WHERE PHYSICS>11 AND CHEMISTRY > 11 AND MATHEMATICS >24;
6)  ALTER TABLE STUDENT_22_BLESSON ADD TOTALMARK INT; UPDATE STUDENT_22_BLESSON SET TOTALMARK=MATHEMATICS+PHYSICS+CHEMISTRY;
    ALTER TABLE STUDENT_22_BLESSON ADD STATUS VARCHAR(20);
    UPDATE STUDENT_22_BLESSON SET STATUS=’FAIL’ WHERE CHEMISTRY<12 OR MATHEMATICS <25 OR PHYSICS <12;
    UPDATE STUDENT_22_BLESSON SET STATUS=’PASS’ WHERE CHEMISTRY>11 OR MATHEMATICS >24 OR PHYSICS >11;
    SELECT * FROM STUDENT_22_BLESSON ORDER BY TOTALMARK DESC;
7) SELECT (COUNT(MATHEMATICS))/10*100 FROM STUDENT_22_BLESSON WHERE MATHEMATICS>24;
8) SELECT (COUNT(S_NAME))/10*100 AS ALL_PASS FROM STUDENT_22_BLESSON WHERE PHYSICS>11 AND CHEMISTRY > 11 AND MATHEMATICS >24;
9) SELECT AVG(TOTALMARK) FROM STUDENT_22_BLESSON;
10) SELECT COUNT(STATUS) FROM STUDENT_22_BLESSON WHERE STATUS=’PASS’;